

[project]
name = "application"
version = "0.1.0"
description = "test application"
authors = [{ name = "Andreas Ernst", email = "andreas.ernst7@assaia.com" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = [
    "aspyx_service>=0.11.5",
    #"cube>=0.1.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
source = "src"

[tool.hatch.build.targets.wheel]
packages = ["src/application"]

[tool.hatch.envs.test]
dependencies = [
  ".",
  "pytest",
  "pytest-cov",
  "pytest-asyncio",
  "anyio",
  "PyJWT"
]

[tool.hatch.metadata]
allow-direct-references = true
